import {
  Typography,
  Link as MuiLink,
  Button,
  CssBaseline,
  ThemeProvider,
} from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import client from "../lib/client";
import Features from "../src/components/Features";
import Footer from "../src/components/Footer";
import Hero from "../src/components/Hero";
import HomeYoutube from "../src/components/HomeYoutube";
import Statistics from "../src/components/Statistics";
import theme from "../src/theme";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>10N8E</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Hero />
      <HomeYoutube />
      <Features />
      <Statistics />
      <Footer />
    </div>
  );
}
