import { Typography, Link as MuiLink, Button } from "@mui/material";
import Head from "next/head";
import Link from "next/link";
import client from "../lib/client";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nexal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h3">Welcome To Nexal</Typography>

      <Link href="/products">
        <Button>Go To Products</Button>
      </Link>
    </div>
  );
}
